spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/children-kitchen?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: "${SQL_PASS}"

  #property for upload pictures
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect


    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

#  mail:
#    host: localhost
#    port: 1025
#    username: "${GMAIL_USER}"
#    password: ""
  mail:
    host: smtp.gmail.com
    username: "${GMAIL_USER}"
    password: "${GMAIL_PASS}"
    port: 587

cloudinary:
  cloud-name: "${CLOUDINARY_NAME}"
  api-key: "${API_KEY}"
  api-secret: "${CLOUDINARY_SECRET}"